### PR TITLE
adding new resource to verification bulk insert

### PR DESCRIPTION
**Pull request by Luitame**
I wrote a new resource to [verification bulk insert](https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/insertDomainVerification.htm) Address.

### CODE REVIEW

**Comment by Luitame** [comment]
[Create an abstraction layer to sync pets with Salesforce](https://trello.com/c/KuPyjpIy/216-create-an-abstraction-layer-to-sync-pets-with-salesforce)

**Review by ianrodrigues — COMMENTED** [review]
@Luitame Can we have a better name than `$dETable` and `$dEColumn`? I didn't get what those mean.

**Comment by Luitame** [comment]
Yes, for sure @ianrodrigues. I only followed the names on the Salesforce documentation.

**Comment by Luitame** [comment]
@ianrodrigues Can you take a look again?

**Pull request merged**
